#!/usr/bin/env bash
# Create a TWIC data archive for new developer bootstrapping.
#
# Archives all PGN files + FIDE ratings + download metadata into a single zip.
# The processed/ directory is excluded (regenerated by `npm run fide-pipeline -- process`).
#
# Usage:
#   bash scripts/create-twic-archive.sh
#   # or: npm run twic-archive
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_DIR="$REPO_ROOT/packages/fide-pipeline/data"
DATE=$(date +%Y%m%d)
ARCHIVE="$REPO_ROOT/twic-archive-${DATE}.zip"

if [ ! -d "$DATA_DIR" ]; then
  echo "Error: Data directory not found: $DATA_DIR"
  echo "Run the pipeline first: npm run fide-pipeline -- download --from 924 --to 1633"
  exit 1
fi

PGN_COUNT=$(ls "$DATA_DIR"/*.pgn 2>/dev/null | wc -l | tr -d ' ')
if [ "$PGN_COUNT" -eq 0 ]; then
  echo "Error: No PGN files found in $DATA_DIR"
  exit 1
fi

echo "Creating TWIC archive..."
echo "  PGN files: $PGN_COUNT"

cd "$DATA_DIR"

# Build file list: all PGNs + ratings + metadata
FILES_TO_ZIP=$(ls *.pgn 2>/dev/null)

if [ -f "download-meta.json" ]; then
  FILES_TO_ZIP="$FILES_TO_ZIP download-meta.json"
fi

if [ -f "ratings/players_list.zip" ]; then
  FILES_TO_ZIP="$FILES_TO_ZIP ratings/players_list.zip"
  echo "  FIDE ratings: included"
fi

zip -j "$ARCHIVE" $FILES_TO_ZIP

echo ""
echo "Archive created: $ARCHIVE"
echo "  Size: $(du -h "$ARCHIVE" | cut -f1)"
echo "  Files: $(unzip -l "$ARCHIVE" | grep -c '\.pgn$') PGN files + extras"
echo ""
echo "To use this archive for dev setup:"
echo "  mkdir -p packages/fide-pipeline/data/ratings"
echo "  cd packages/fide-pipeline/data"
echo "  unzip /path/to/twic-archive-${DATE}.zip"
echo "  mv players_list.zip ratings/"
